apiVersion: v1
kind: Namespace
metadata:
  name: ham
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ham-gh-deployer
  namespace: ham
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ham-gh-deployer-namespaced
subjects:
  - kind: ServiceAccount
    name: ham-gh-deployer
    namespace: ham-cicd
