name: Deploy to ham.weiham.com

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release image tag"
        required: true
        type: string

permissions:
  contents: read
  deployments: write

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://ham.weiham.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"
      - name: Configure kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          printf "%s" "$KUBE_CONFIG" > ~/.kube/config
          kubectl config current-context
      - name: Deploy
        env:
          HELM_DRIVER: configmap
        run: |
          set -euo pipefail
          helm upgrade --install ham do/deploy \
            -n ham \
            -f do/deploy/values.yaml \
            --set backend.tag="${{ inputs.tag }}" \
            --set web.tag="${{ inputs.tag }}" \
            --atomic --timeout 10m
      - name: Post-deploy status
        env:
          HELM_DRIVER: configmap
        run: |
          echo "Helm status:"
          helm -n ham status ham || true
          echo
          echo "Workload summary:"
          kubectl -n ham get deploy,sts,ds,svc,ingress,pods -o wide
          echo
          echo "Rollout status (deployments):"
          for d in $(kubectl -n ham get deploy -o jsonpath='{.items[*].metadata.name}'); do
            echo ">> $d"
            kubectl -n ham rollout status deploy/$d --timeout=120s || true
          done
